In [1]:
import torch
print("Is CUDA ready?", torch.cuda.is_available())

Is CUDA ready? True


In [2]:
x = torch.rand(3, 3)
print(x)

tensor([[0.7904, 0.1675, 0.6956],
        [0.7281, 0.7549, 0.4142],
        [0.4726, 0.9574, 0.9635]])


In [4]:
y = torch.ones_like(x, device="cuda")
x = x.to("cuda")

In [6]:
z = x + y
print(z)

tensor([[1.7904, 1.1675, 1.6956],
        [1.7281, 1.7549, 1.4142],
        [1.4726, 1.9574, 1.9635]], device='cuda:0')


In [7]:
z = z.to("cpu")
print(z)

tensor([[1.7904, 1.1675, 1.6956],
        [1.7281, 1.7549, 1.4142],
        [1.4726, 1.9574, 1.9635]])


In [8]:
s = 10000
device = "cpu"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)

%time z = torch.matmul(x, y)

CPU times: user 14.1 s, sys: 188 ms, total: 14.3 s
Wall time: 7.53 s


In [10]:
s = 10000
device = "cuda"
x = torch.rand(s, s, device=device, dtype=torch.float32)
y = torch.rand(s, s, device=device, dtype=torch.float32)

%time z = torch.matmul(x, y); torch.cuda.synchronize()

CPU times: user 374 ms, sys: 204 ms, total: 577 ms
Wall time: 576 ms
